services:
  - type: web
    name: aion-fastapi
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
build:
  environment:
    pythonVersion: 3.11
